#!/usr/bin/env python3
"""Generates Sources/NyxCore/Unicode/WidthTable.swift from Unicode 16 data files."""
import re, urllib.request, os

BASE = "https://www.unicode.org/Public/16.0.0/ucd/"
FILES = {
    "eaw": BASE + "EastAsianWidth.txt",
    "gc": BASE + "extracted/DerivedGeneralCategory.txt",
    "emoji": BASE + "emoji/emoji-data.txt",
}

def fetch(url):
    with urllib.request.urlopen(url, timeout=30) as r:
        return r.read().decode("utf-8")

def parse(text, wanted):
    """Yields (lo, hi) for lines whose property value is in `wanted`."""
    for line in text.splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        rng, prop = [p.strip() for p in line.split(";")[:2]]
        if prop not in wanted:
            continue
        if ".." in rng:
            lo, hi = rng.split("..")
        else:
            lo = hi = rng
        yield int(lo, 16), int(hi, 16)

def merge(ranges):
    out = []
    for lo, hi in sorted(ranges):
        if out and lo <= out[-1][1] + 1:
            out[-1] = (out[-1][0], max(out[-1][1], hi))
        else:
            out.append((lo, hi))
    return out

def subtract(ranges, cp):
    out = []
    for lo, hi in ranges:
        if lo <= cp <= hi:
            if lo < cp: out.append((lo, cp - 1))
            if cp < hi: out.append((cp + 1, hi))
        else:
            out.append((lo, hi))
    return out

eaw = fetch(FILES["eaw"]); gc = fetch(FILES["gc"]); emoji = fetch(FILES["emoji"])

wide = list(parse(eaw, {"W", "F"})) + list(parse(emoji, {"Emoji_Presentation"}))
zero = list(parse(gc, {"Mn", "Me", "Cf"})) + [(0x1160, 0x11FF), (0x200B, 0x200F), (0x2028, 0x2029), (0x2060, 0x206F)]
wide = merge(wide)
zero = subtract(merge(zero), 0x00AD)  # soft hyphen renders as a visible dash in terminals
# a code point cannot be both: zero wins
wide_only = []
for lo, hi in wide:
    cur = lo
    for zlo, zhi in zero:
        if zhi < cur or zlo > hi: continue
        if zlo > cur: wide_only.append((cur, zlo - 1))
        cur = zhi + 1
    if cur <= hi: wide_only.append((cur, hi))
wide = merge(wide_only)

def swift_array(name, ranges):
    body = ",\n".join("        0x%04X, 0x%04X" % r for r in ranges)
    return "    static let %s: [UInt32] = [\n%s,\n    ]\n" % (name, body)

out = "// Generated by scripts/gen_width_table.py from Unicode 16.0.0. Do not edit.\n\n"
out += "enum WidthTable {\n" + swift_array("wide", wide) + "\n" + swift_array("zero", zero) + "}\n"
path = os.path.join(os.path.dirname(__file__), "..", "Sources", "NyxCore", "Unicode", "WidthTable.swift")
os.makedirs(os.path.dirname(path), exist_ok=True)
with open(path, "w") as f:
    f.write(out)
print("wrote", path, len(wide), "wide ranges,", len(zero), "zero ranges")
